name: Sync Glitch

on:
  pull_request:
    types: [closed]

jobs:
  sync_glitch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v1.1.2
        with:
          node-version: 12.x
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: yarn lint
      - run: yarn typecheck
      - name: Run sync-glitch
        env:
          GLITCH_PROJECT_ID: ${{ secrets.GLITCH_PROJECT_ID }}
          GLITCH_TOKEN: ${{ secrets.GLITCH_TOKEN }}
          GH_REPO: ${{ secrets.GH_REPO }}
        run: |
          echo ${GLITCH_PROJECT_ID}
          echo ${GLITCH_TOKEN}
          echo ${GH_REPO}
          GLITCH_PROJECT_ID=${GLITCH_PROJECT_ID} GLITCH_TOKEN=${GLITCH_TOKEN} GH_REPO=${GH_REPO} yarn sync-glitch
